import os.path
from pythonci.task import BaseTask


NUMPY_ZIP = 'https://files.pythonhosted.org/packages/84/1e/ff467ac56bfeaea51d4a2e72d315c1fe440b20192fea7e460f0f248acac8/numpy-1.18.2.zip'



class Task(BaseTask):
    name = "numpy"

    def _install(self):
        # rely on Fedora to provide OpenBLAS or pull it differently?

        if self.app.args.dev:
            url = "git+git://github.com/cython/cython.git@a32a29e8aaa688e0507d374ab47e641eb1a427c4#egg=Cython"
            self.app.run_python(["-m", "pip", "install", url])
        else:
            self.app.pip_install_update(["Cython"])

        self.app.download_extract_zip(NUMPY_ZIP, self.dirname)
        self.app.chdir(self.dirname)

        # Force to run Cython: regenerate C files generated by Cython
        cmd = r"rm -f -v $(grep -rl '/\* Generated by Cython') PKG-INFO"
        self.app.run_command([cmd], shell=True, cwd=self.dirname)

        self.app.run_python(["setup.py", "install"], cwd=self.dirname)

        self.app.pip_install_update(["nose", "pytest"])

    def _run_tests(self):
        script = os.path.join(self.dirname, 'tools', 'test-installed-numpy.py')
        self.app.run_python([script, "--mode=full"])
